### ISSUE TITLE
How to get the emotion words and generic words ?

### ISSUE THREAD

**Issue by sxqqslf** [tuxchow/ecm#3]
你好，请问情感词和一般词是怎么获取的，麻烦可以提供这个数据的下载链接吗

**Comment by tuxchow** [comment]
我们使用的是大连理工大学信息检索研究室中文情感词汇本体库
下载链接为 http://ir.dlut.edu.cn/news/detail/215

**Comment by bearblog** [comment]
> 我们使用的是大连理工大学信息检索研究室中文情感词汇本体库
> 下载链接为 http://ir.dlut.edu.cn/news/detail/215

请问vocab40000.ememory文件的里数据的是否有顺序？是否是按以下的顺序？

- 0：Other
- 1: Like
- 2: Sadness
- 3: Disgust
- 4: Anger
- 5: Happiness

大连理工大学信息检索研究室中文情感词汇本体库中有7类情感，请问Other类的情感是怎么确定的？
十分感谢！

**Comment by tuxchow** [comment]
是的，Other 类为 Like，Sadness，Disgust，Anger，Happiness 类别之外的词
