### ISSUE TITLE
关于ememory_vocab_file和vector.txt

### ISSUE THREAD

**Issue by njuzrs** [tuxchow/ecm#5]
作者您好，读了您的论文之后感觉非常有意思，想复现一遍。但是在复现的时候遇到了缺少ememory_vocab_file和vector.txt这两个文件，其中vector.txt代码中可以随机生成，但是ememory_vocab_file是需要提供的，请问是否能提供这两个文件的下载地址？

**Comment by tuxchow** [comment]
ememory 存储的是各个情绪词的列表，格式为[[word1_of_emotion1, word2_of_emotion1,…], [word1_of_emotion2, word2_of_emotion2, …], …]，根据情感词典创建（详见论文），不同数据集需要构建不同的情绪词的列表​​。

**Comment by njuzrs** [comment]
了解了谢谢！另外请问您在训练模型的时候，vector.txt是预训练好的词向量吗？

**Comment by njuzrs** [comment]
另外我在把ememory加进模型训练之后，出现了如下错误：
File "/home/zhangrongsheng/ecm2/baseline.py", line 235, in train
    target_weights, decoder_emotions, bucket_id, False, False)
  File "/home/zhangrongsheng/ecm2/seq2seq_model.py", line 223, in step
    outputs = session.run(output_feed, input_feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: model_with_buckets/embedding_attention_seq2seq_1/embedding_attention_decoder/attention_decoder/Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](model_with_buckets/embedding_attention_seq2seq_1/embedding_attention_decoder/attention_decoder/transpose_1, model_with_buckets/embedding_attention_seq2seq_1/embedding_attention_decoder/attention_decoder/concat_3)]]
	 [[Node: global_norm_1/global_norm/_979 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="e
尽管我缩小hidden的大小和vocab的大小都还是报这个错，去掉use_ememory就可以运行，请问您是否遇到过这个错误？

**Comment by MrSeven77** [comment]
作者您好，请问能公开部分ememory_vocab_file用于学习吗？

**Comment by tuxchow** [comment]
[["_PAD", "_UNK", "_EOS", "_GO", "，", "。", "的", "！", "了", "是", "一", "？", "我", "你", "#", "不", "有", ..., "后知后觉"], ["热潮", "盛开", "无上", "新意", "信奉", "技艺", "坚守", "见闻", "解惑", "箴言", "指导", "致敬", "精妙", ..., "新鲜"], ["坠毁", "寸草不生", "先烈", "思念", "悲哀", "悲伤", "倒霉", "叹息", "悔恨", "死心", "同归于尽", "单相思", "无语", "萧瑟", "身不由己", ..., "打击"], ["阻力", "不雅", "寡断", "灰蒙蒙", "急死", "介意", "彷徨", "恨不得", "迷糊", "一塌糊涂", "弱智", "浅显", "败类", "批评", "脱轨", ..., "小子"], ["失落", "悲愤", "阴沉", "投诉", "火气", "愤怒", "恼火", "滚出去", "抗议", "气愤", "MD", "真TM", "发脾气", "拍案", "羞辱", "爆发", "发指", ..., "发怒"], ["瑞雪", "喜人", "安好", "特等", "欢快", "如意", "庆幸", "喜气", "快意", "嫣然", "安逸", "海阔天空", "CC", "超爽", "高升", "回归", ..., "增生"]]

**Comment by Kiteflyingee** [comment]
请问下Vector.txt是怎样生成的。

**Comment by Learner-8bit** [comment]
> 

Delete “...” will solve this problem.
